FROM localhost/distroless-from-scratch/java-centos8:8 as base

FROM docker.io/centos:centos8 AS builder
RUN mkdir --parents /tmp/copy
COPY --from=base /packages.txt /tmp/copy
COPY \
    scripts/add_busybox.sh \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/rpm_extract_packages.sh \
    scripts/yum_download_packages.sh \
    /tmp
RUN : \
    && /tmp/add_busybox.sh \
    && /tmp/yum_download_packages.sh \
        java-1.8.0-openjdk-devel.x86_64 \
    && /tmp/rpm_extract_packages.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM localhost/distroless-from-scratch/java-centos8:8
COPY --from=builder /tmp/copy ./
