FROM localhost/distroless-from-scratch/cc-opensuseleap15:latest as base

FROM docker.io/opensuse/leap:15 AS builder
RUN mkdir --parents /tmp/copy
COPY --from=base /packages.txt /tmp/copy
COPY \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/link_java_executable.sh \
    scripts/rpm_extract_packages.sh \
    scripts/zypper_download_packages.sh \
    /tmp
RUN : \
    && /tmp/zypper_download_packages.sh \
        dejavu-fonts \
        fontconfig \
        java-1_8_0-openjdk-headless \
        libexpat1 \
        libfreetype6 \
        libjpeg8 \
        liblcms2-2 \
        libpng16-16 \
        libuuid1 \
        libz1 \
    && /tmp/rpm_extract_packages.sh \
    && /tmp/link_java_executable.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM localhost/distroless-from-scratch/cc-opensuseleap15:latest
COPY --from=builder /tmp/copy ./
ENTRYPOINT ["/usr/bin/java", "-jar"]
ENV JAVA_VERSION=8
ENV LANG=C.UTF-8
