FROM docker.io/centos:centos8 AS builder
COPY \
    scripts/add_nonroot.sh \
    scripts/add_nsswitch.sh \
    scripts/add_users_and_groups.sh \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/rpm_extract_packages.sh \
    scripts/yum_download_packages.sh \
    /tmp/
RUN : \
    && /tmp/yum_download_packages.sh \
        centos-linux-release.noarch \
        ca-certificates.noarch \
        filesystem.x86_64 \
        setup.noarch \
        tzdata.noarch \
    && /tmp/rpm_extract_packages.sh \
    && /tmp/add_users_and_groups.sh \
    && /tmp/add_nonroot.sh \
    && /tmp/add_nsswitch.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM scratch
COPY --from=builder /tmp/copy ./
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
USER 0:0
WORKDIR /
