FROM localhost/distroless-from-scratch/base-opensuseleap15:latest as base

FROM docker.io/opensuse/leap:15 AS builder
RUN mkdir --parents /tmp/copy/var/lib/rpm
COPY --from=base /packages.txt /tmp/copy/
COPY --from=base /var/lib/rpm /tmp/copy/var/lib/rpm
COPY \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/rpm_extract_packages.sh \
    scripts/zypper_download_packages.sh \
    /tmp/
RUN : \
    && /tmp/zypper_download_packages.sh \
        libgcc_s1 \
        libgomp1 \
        libstdc++6 \
    && /tmp/rpm_extract_packages.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM localhost/distroless-from-scratch/base-opensuseleap15:latest
COPY --from=builder /tmp/copy ./
