FROM localhost/distroless-from-scratch/static-alpine3:latest as base

FROM docker.io/alpine:3 AS builder
RUN mkdir --parents /tmp/copy
COPY --from=base /packages.txt /tmp/copy/
COPY \
    scripts/apk_download_packages.sh \
    scripts/apk_install_packages.sh \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/tar_extract_packages.sh \
    /tmp/
RUN : \
    && /tmp/apk_install_packages.sh \
        bash \
    && /tmp/apk_download_packages.sh \
        libcrypto1.1 \
        libssl1.1 \
        musl \
        openssl \
    && /tmp/tar_extract_packages.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM localhost/distroless-from-scratch/static-alpine3:latest
COPY --from=builder /tmp/copy ./
