FROM localhost/distroless-from-scratch/cc-debian10:latest as base

FROM docker.io/debian:10.7-slim AS builder
RUN mkdir --parents /tmp/copy
COPY --from=base /packages.txt /tmp/copy/
COPY \
    scripts/apt_download_packages.sh \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/dpkg_extract_packages.sh \
    /tmp/
RUN : \
    && /tmp/apt_download_packages.sh \
        libatomic1 \
        libbrotli1 \
        libc-ares2 \
        libicu63 \
        libnode64 \
        libuv1 \
        nodejs \
        npm \
        zlib1g \
    && /tmp/dpkg_extract_packages.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM localhost/distroless-from-scratch/cc-debian10:latest
COPY --from=builder /tmp/copy ./
ENTRYPOINT ["/usr/bin/node"]
