FROM localhost/distroless-from-scratch/cc-debian10:latest as base

FROM docker.io/debian:10.7-slim AS builder
RUN mkdir --parents /tmp/copy
COPY --from=base /packages.txt /tmp/copy/
COPY \
    scripts/add_java_certificates.sh \
    scripts/add_openjdk8_repository.sh \
    scripts/apt_download_packages.sh \
    scripts/apt_install_packages.sh \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/dpkg_extract_packages.sh \
    scripts/link_java_executable.sh \
    /tmp/
RUN : \
    && /tmp/apt_install_packages.sh \
        curl \
        gnupg \
        software-properties-common \
    && /tmp/add_openjdk8_repository.sh \
    && /tmp/apt_download_packages.sh \
        adoptopenjdk-8-hotspot-jre \
        ca-certificates-java \
        fontconfig-config \
        fonts-dejavu-core \
        libc-bin \
        libexpat1 \
        libfontconfig1 \
        libfreetype6 \
        libjpeg62-turbo \
        liblcms2-2 \
        libpng16-16 \
        libuuid1 \
        zlib1g \
    && /tmp/dpkg_extract_packages.sh \
    && /tmp/apt_install_packages.sh \
        adoptopenjdk-8-hotspot-jre \
        ca-certificates-java \
    && /tmp/add_java_certificates.sh \
    && /tmp/link_java_executable.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM localhost/distroless-from-scratch/cc-debian10:latest
COPY --from=builder /tmp/copy ./
ENTRYPOINT ["/usr/bin/java", "-jar"]
ENV JAVA_VERSION=8
ENV LANG=C.UTF-8
