FROM localhost/distroless-from-scratch/base-centos8:latest as base

FROM docker.io/centos:centos8 AS builder
RUN mkdir --parents /tmp/copy
COPY --from=base /packages.txt /tmp/copy/
COPY \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/rpm_extract_packages.sh \
    scripts/yum_download_packages.sh \
    /tmp/
RUN : \
    && /tmp/yum_download_packages.sh \
        libgcc.x86_64 \
        libgomp.x86_64 \
        libstdc++.x86_64 \
    && /tmp/rpm_extract_packages.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM localhost/distroless-from-scratch/base-centos8:latest
COPY --from=builder /tmp/copy ./
