FROM localhost/distroless-from-scratch/cc-alpine3:latest as base

FROM docker.io/alpine:3 AS builder
RUN mkdir --parents /tmp/copy
COPY --from=base /packages.txt /tmp/copy/
COPY \
    scripts/apk_download_packages.sh \
    scripts/apk_install_packages.sh \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/link_java_executable.sh \
    scripts/tar_extract_packages.sh \
    /tmp
RUN : \
    && /tmp/apk_install_packages.sh \
        bash \
    && /tmp/apk_download_packages.sh \
        java-cacerts \
        openjdk11-jre-headless \
        zlib \
    && /tmp/tar_extract_packages.sh \
    && /tmp/link_java_executable.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM localhost/distroless-from-scratch/cc-alpine3:latest
COPY --from=builder /tmp/copy ./
ENTRYPOINT ["/usr/bin/java", "-jar"]
ENV JAVA_VERSION=11
ENV LANG=C.UTF-8
