FROM localhost/distroless-from-scratch/base-debian10:latest as base

FROM docker.io/debian:10.7-slim AS builder
RUN mkdir --parents /tmp/copy
COPY --from=base /packages.txt /tmp/copy/
COPY \
    scripts/apt_download_packages.sh \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/dpkg_extract_packages.sh \
    /tmp/
RUN : \
    && /tmp/apt_download_packages.sh \
        libgcc1 \
        libgomp1 \
        libstdc++6 \
    && /tmp/dpkg_extract_packages.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM localhost/distroless-from-scratch/base-debian10:latest
COPY --from=builder /tmp/copy ./
