FROM localhost/distroless-from-scratch/java-debian10:11 as base

FROM docker.io/debian:10.7-slim AS builder
RUN mkdir --parents /tmp/copy
COPY --from=base /packages.txt /tmp/copy/
COPY \
    scripts/apt_download_packages.sh \
    scripts/change_timestamps_to_unix_epoch.sh \
    scripts/dpkg_extract_packages.sh \
    scripts/link_busybox.sh \
    /tmp/
RUN : \
    && /tmp/apt_download_packages.sh \
        busybox-static \
        openjdk-11-jdk-headless \
    && /tmp/dpkg_extract_packages.sh \
    && /tmp/link_busybox.sh \
    && /tmp/change_timestamps_to_unix_epoch.sh \
    && :

FROM localhost/distroless-from-scratch/java-debian10:11
COPY --from=builder /tmp/copy ./
